def run_supervised(): 
    print("Running supervised pipeline...")
    
    """supervised.ipynb
    
    Automatically generated by Colab.
    
    Original file is located at
        https://colab.research.google.com/drive/1sQvKwiDqsCrZWo8vQhbxFC3seUPEQdFh
    
    # **ML PROJECT - EEG PD**
    ## Imports & Configuration
    """
    
    # General Purpose Libraries
    import os
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    import seaborn as sns
    import warnings
    import mne
    import gdown
    import shap
    import copy
    import umap
    warnings.filterwarnings("ignore", category=RuntimeWarning)
    warnings.filterwarnings("ignore")
    sns.set(style="whitegrid")
    from tqdm import tqdm
    
    import plotly.express as px
    from matplotlib.lines import Line2D
    
    from scipy.stats import mode, pearsonr, entropy, pointbiserialr, zscore, spearmanr, wilcoxon, kruskal
    import scipy.stats as stats
    from scipy.spatial import ConvexHull
    from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
    from scipy.spatial.distance import pdist, squareform
    from sklearn.linear_model import LinearRegression
    from sklearn.manifold import TSNE
    from scipy.integrate import trapezoid
    from scipy.signal import spectrogram
    
    from mne.time_frequency import psd_array_welch
    from sklearn.neighbors import NearestNeighbors
    from random import sample
    
    from IPython.display import Markdown, display
    from imblearn.pipeline import Pipeline as ImbPipeline
    from imblearn.over_sampling import SMOTE
    
    import scikit_posthocs as sp
    
    from sklearn.base import clone
    from sklearn.calibration import calibration_curve, CalibratedClassifierCV
    from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
    from sklearn.decomposition import PCA
    from sklearn.pipeline import Pipeline
    from sklearn.linear_model import LogisticRegression
    from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
    from sklearn.mixture import GaussianMixture
    from sklearn.metrics import (
    	silhouette_score, davies_bouldin_score, calinski_harabasz_score,
    	adjusted_rand_score, normalized_mutual_info_score, f1_score, confusion_matrix, ConfusionMatrixDisplay, recall_score, precision_score,
    	classification_report, accuracy_score, roc_curve, auc, roc_auc_score, RocCurveDisplay, make_scorer, balanced_accuracy_score
    )
    from sklearn.model_selection import StratifiedKFold, train_test_split, cross_val_score, GroupKFold, cross_validate, GroupShuffleSplit, cross_val_predict, GridSearchCV
    from sklearn.ensemble import RandomForestClassifier, IsolationForest, GradientBoostingClassifier
    from sklearn.svm import SVC
    
    import sys
    from pathlib import Path
    
    # Detect Colab
    IN_COLAB = "google.colab" in sys.modules
    
    if IN_COLAB:
        from google.colab import drive
        drive.mount("/content/drive")  # Mount Drive first
    
        # Path to your project folder in Drive
        PROJECT_ROOT = Path("/content/drive/MyDrive/ML_RS_EEG")
    
        # Make sure Python can find utils.py
        sys.path.append(str(PROJECT_ROOT))
    
    else:
        # Local machine
        PROJECT_ROOT = Path.cwd()
        sys.path.append(str(PROJECT_ROOT))
    
    import utils
    
    plt.ioff()
    RANDOM_STATE = utils.RANDOM_STATE
    
    """All models are fixed with a random seed to ensure reproducibility. Importantly, the analysis deliberately relies on **multiple clustering algorithms and dimensionality reduction techniques** to avoid conclusions driven by a single method."""
    
    PROJECT_ROOT, DATA_ROOT, csv_path = utils.setup_environment()
    
    """# 1. DATASET LOADING, DEFINITION & SANITY CHECKS
    
    The dataset consists of **resting-state EEG recordings** from Parkinson’s disease patients and healthy controls. The overarching goal of the unsupervised analysis is **not classification**, but rather to characterize the **intrinsic geometry** of EEG feature space.
    
    ## Sanity checks
    """
    
    raw_csv = pd.read_csv(csv_path)
    
    set_files = sorted(DATA_ROOT.glob("sub-*/eeg/*.set"))
    
    print(f"Subjects found: {len(set_files)}")
    print(f"First 3 EEG files: {set_files[:3]}")
    
    # Load one example recording (sanity check only)
    example_file = set_files[0]
    raw = mne.io.read_raw_eeglab(example_file, preload=False, verbose=False)
    
    print("Sampling frequency:", raw.info["sfreq"])
    print("Number of channels:", len(raw.ch_names))
    print("Duration (seconds):", raw.n_times / raw.info["sfreq"])
    print("First 10 channel names:", raw.ch_names[:10])
    
    # Visual inspection (not used later)
    raw.plot(n_channels=20, start=10, duration=10, scalings="auto")
    raw.plot_sensors(show_names=True)
    
    psd = raw.compute_psd(method="welch", fmin=0.5, fmax=50, verbose=False)
    psd.plot(dB=True)
    
    """## Participants, labels and cognitive scores
    
    We ask whether latent structure emerges naturally from the data, and if so, whether this structure aligns with disease diagnosis or clinical variables such as age, cognition (MOCA), or motor severity (UPDRS).
    """
    
    cognitive_cols = ['NIH FICAT', 'NIH DCCST', 'NIH PCPST', 'NIH PSMT','NIH PVT']
    
    # Keep only rows where all cognitive tests are not NaN
    participants, set_files, valid_subjects = utils.sync_eeg_and_metadata(raw_csv, DATA_ROOT)
    subs_list = valid_subjects
    
    print(participants["GROUP"].value_counts())
    
    age = participants.loc[participants["participant_id"].isin([f.parts[-3] for f in set_files]),"AGE"].values
    moca = participants.loc[participants["participant_id"].isin([f.parts[-3] for f in set_files]),"MOCA"].values
    updrs = participants.loc[participants["participant_id"].isin([f.parts[-3] for f in set_files]),"UPDRS"].values
    nih_ficat = participants.loc[participants["participant_id"].isin([f.parts[-3] for f in set_files]),"NIH FICAT"].values
    
    
    # Sanity check
    if len(age) == len(valid_subjects):
      print("AGE vector shape:", age.shape)
    else:
      raise ValueError("AGE vector length mismatch")
    
    y_true = participants.set_index("participant_id").loc[valid_subjects, "GROUP"].values
    
    """Labels are loaded here for bookkeeping and post hoc evaluation only.
    They are not used in feature construction or clustering.
    """
    
    subject_info = participants.copy()
    sns.pairplot(subject_info[['AGE', 'MOCA', 'UPDRS', 'NIH FICAT', 'NIH DCCST', 'NIH PCPST', 'NIH PSMT','NIH PVT','GROUP']], hue="GROUP", palette={"PD":'Red' , "Control": 'Blue'})
    
    plt.show()
    
    """## Common channels"""
    
    def load_eeg(file_path: Path) -> mne.io.Raw:
      # Load using mne
      return mne.io.read_raw_eeglab(
        file_path,
        preload=True,
        verbose=False
      )
    
    # Determine common channel set (intersection across subjects)
    common_channels = utils.get_common_channels(set_files)
    print(f"There are {len(common_channels)} channels common to all {len(set_files)} subjects.")
    
    print(utils.SELECTED_CHANNELS)
    
    """## Domain specific cognitive score + Processing"""
    
    # Check how well the NIH scores correlate with each other
    internal_corr = participants[cognitive_cols].corr()
    
    sns.heatmap(internal_corr, annot=True, cmap='viridis')
    plt.title("Internal Correlation of Cognitive Domains")
    plt.show()
    
    """FICAT, DCCST, and PCPST are all strongly inter-correlated ($0.45$ to $0.55$). These three tests (Inhibitory Control, Cognitive Flexibility, and Processing Speed) are clearly moving together. They represent a "Frontal-Executive" core.PSMT and PVT have much weaker ties to that core (dropping as low as $0.18$). These measure Memory and Vocabulary/Vision, which are likely being preserved or affected differently in the group."""
    
    # Z-scores for EVERYONE based on Control Norms
    participants = utils.get_processed_participants(participants)
    
    print(f"-  CLINICAL LABEL SUMMARY (N={len(participants)})  -")
    print("\nGroup Breakdown of Tiers (0=Preserved, 1=Standard, 2=Impaired):")
    print(participants.groupby('GROUP')['cog_tier'].value_counts().unstack().fillna(0).astype(int))
    
    print()
    print("Binary Distribution (1=Impaired, 0=Not_Impaired):")
    binary_counts = participants.groupby('GROUP')['cog_binary'].value_counts().unstack().fillna(0).astype(int)
    binary_counts.columns = ['Not_Impaired (0)', 'Impaired (1)']
    print(binary_counts)
    
    """To establish a biologically grounded ground-truth for cognitive status, participants were categorized using a normative-referenced composite score targeting the executive function domain. Recognizing that Inhibitory Control (FICAT), Cognitive Flexibility (DCCST), and Processing Speed (PCPST) exhibited strong inter-correlation ($r = 0.45$ to $0.55$), an Executive Composite was calculated. This was achieved by transforming raw scores into Z-scores based exclusively on the distribution of the Healthy Control cohort ($N=46$). By using the healthy population as the baseline yardstick, we ensured that "Impairment" was defined not by arbitrary clusters, but by significant deviation from neurotypical performance. Specifically, a threshold of $Z < -1.0$ (representing the bottom 15% of healthy performance) was used to define Clinical Impairment (Tier 0), while $Z \ge 0$ identified Preserved function (Tier 2). This rigorous stratification provides a stable clinical anchor for the subsequent unsupervised EEG clustering, allowing us to test whether natural brain-wave patterns respect these established clinical boundaries.
    
    # 2. FEATURE CONSTRUCTION
    
    ## Feature construction
    
    Multiple feature representations are constructed to probe EEG structure at different levels of abstraction. This includes high-dimensional spectral representations as well as biologically motivated low-frequency summaries. Importantly, features are constructed **per channel × band**, preserving spatial information and enabling interpretability of latent axes.
    
    If we focus on known PD-sensitive frequencies, does diagnostic separation improve?
    Prior work identified the 0.5–12 Hz range as maximally discriminative between PD and control subjects, spanning delta, theta, and low-alpha bands known to be abnormal in PD.
    
    LEAPD bandpower features were included as a hypothesis-driven, disease-optimized representation, complementary to generic spectral features. This allows us to assess whether unsupervised structure aligns more strongly with PD-specific spectral abnormalities or emerges independently of disease-informed feature design.
    """
    
    FEATURES = utils.construct_master_features(set_files, utils.SELECTED_CHANNELS)
    
    print()
    print("-  FINAL INTEGRITY CHECK  -")
    for key, data in FEATURES.items():
      print(f"Set: {key} | Shape: {data.shape}")
    
    profile_cols = utils.get_feature_names()
    # Verify the length matches data columns (Should be 33)
    print(f"Total Features: {len(profile_cols)}")
    
    """Sizes ok:
    
    low_freq = $(8 \text{ channels} \times 3 \text{ bands}) + 8 \text{ per-channel TARs} + 1 \text{ Global TAR} = \mathbf{33}$
    
    sham_band =  $(8 \text{ channels} \times 4 \text{ bands}) $ = 32
    
    # SUPERVISED
    
    **Task A:** The Categorical Anchor (GROUP)
    
    Goal: Binary classification (PD vs. HC).
    
    Metric: Nested CV ROC-AUC.Purpose: Establishes the baseline "disease signal" in the EEG.
    
    **Task B:** The Dimensional Gradient (Cognition)
    
    Train: Binary (Impaired vs. Preserved/Standard).
    
    Test/Evaluate: Tiered (Preserved $\rightarrow$ Standard $\rightarrow$ Impaired).
    
    Purpose: Tests if the model captures the progression rather than just a binary state.
    
    ## Model definitions
    """
    
    models = {
        "LogisticRegression": LogisticRegression(max_iter=2000, class_weight="balanced"),
        "LinearSVM": SVC(kernel="linear", class_weight="balanced"),
        "RBFSVM": SVC(kernel="rbf", class_weight="balanced"),
        "RandomForest": RandomForestClassifier(
            n_estimators=300,
            random_state=RANDOM_STATE,
            class_weight="balanced",
        ),
        "GradientBoosting": GradientBoostingClassifier(random_state=RANDOM_STATE),
    }
    
    """## Data preparation"""
    
    def prepare_raw_staged_data(features_dict, participants_df, subs_list):
        # Synchronizes features with labels without global scaling to prevent leakage
        participants_indexed = participants_df.set_index('participant_id')
    
        # Extract Labels
        y_binary = participants_indexed.loc[subs_list, 'cog_binary'].values
        y_tiered = participants_indexed.loc[subs_list, 'cog_tier'].values
        y_diag   = participants_indexed.loc[subs_list, 'GROUP'].values
    
        # Store Raw Features (No Scaling here!)
        features_raw = {}
        for key, matrix in features_dict.items():
            features_raw[key] = matrix
    
        return features_raw, y_binary, y_tiered, y_diag
    
    # Execute preparation
    FEATURES_RAW, y_binary, y_tiered, y_diag = prepare_raw_staged_data(FEATURES, participants, subs_list)
    
    # Targets for Task 1
    y_task1 = np.where(y_diag == "PD", 1, 0)
    # Targets for Task 2
    y_task2 = y_binary
    
    """## Target definition and CV setup"""
    
    OUTER_SPLITS = 5
    INNER_SPLITS = 3
    N_BOOTSTRAPS = 1000
    
    # Task 1: PD diagnosis
    y_pd = participants["GROUP"].map({"Control": 0, "PD": 1}).values
    
    # Task 2: Cognitive Impairment (Binary for training)
    y_cog_bin = participants["cog_binary"].values
    
    y_cog_tiers = participants["cog_tier"].values # We don't train on this, but use it for post-hoc validation
    
    # CV
    # Stratified sampling ensures class balance is maintained across folds
    outer_cv = StratifiedKFold(n_splits=OUTER_SPLITS, shuffle=True, random_state=RANDOM_STATE)
    inner_cv = StratifiedKFold(n_splits=INNER_SPLITS, shuffle=True, random_state=RANDOM_STATE)
    
    # The models will pick the best scaler from this list during the inner loop
    # scaler_grid = [StandardScaler(), RobustScaler(), MinMaxScaler()]
    
    # scoring metrics for all tasks
    scoring = {
        "roc_auc": "roc_auc",
        "balanced_acc": "balanced_accuracy",
        "recall": "recall",
    }
    
    print(f"Section 1 Complete: Targets prepared for {len(y_pd)} subjects.")
    print(f"Class Distribution (PD): {np.bincount(y_pd)}")
    print(f"Class Distribution (Cognitive Impairment): {np.bincount(y_cog_bin)}")
    
    USE_SMOTE = True  # Apply SMOTE inside CV folds only
    SMOTE_K_NEIGHBORS = 5
    
    def build_nested_pipeline(model):
        return ImbPipeline([
            ('scaler', StandardScaler()),
            ('smote', SMOTE(k_neighbors=SMOTE_K_NEIGHBORS, random_state=RANDOM_STATE)),
            ('model', model)
        ])
    
    #
    def build_param_grid(model_name):
        if model_name == "LogisticRegression":
            return {"model__C": [0.1, 1.0, 10.0]}
        elif model_name == "LinearSVM":
            return {"model__C": [0.1, 1.0, 10.0]}
        elif model_name == "RBFSVM":
            return {"model__C": [1.0, 10.0], "model__gamma": ["scale", "auto"]}
        elif model_name == "RandomForest":
            return {
                "model__n_estimators": [200, 400],
                "model__max_depth": [None, 10],
                "model__min_samples_split": [2, 5]
            }
        elif model_name == "GradientBoosting":
            return {
                "model__n_estimators": [100, 200],
                "model__learning_rate": [0.05, 0.1],
                "model__max_depth": [3]
            }
        return {}
    
    def get_scores_for_estimator(estimator, X):
        # Extracts probabilities or decision scores
        if hasattr(estimator, "predict_proba"):
            return estimator.predict_proba(X)[:, 1]
        return estimator.decision_function(X)
    
    def compute_specificity(y_true, y_pred):
        # Calculates TNR (True Negative Rate)
        tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
        return tn / (tn + fp) if (tn + fp) > 0 else 0.0
    
    """## TASK 1
    
    ### Nested CV
    """
    
    # Use RAW features to avoid global leakage
    print("Starting Nested CV (Raw Features + Internal Scaling + SMOTE)...")
    
    # Initialize results
    nested_results = []
    outer_predictions = {}
    
    for family_name, X in FEATURES_RAW.items():
        for model_name, model_instance in models.items():
            fold_auc, fold_recall, fold_spec, fold_bal = [], [], [], []
            y_true_all, y_score_all = [], []
    
            # Get the specific param grid for this model
            param_grid = build_param_grid(model_name)
    
            # Outer Loop: Generalization
            for train_idx, test_idx in outer_cv.split(X, y_task1):
                X_train, X_test = X[train_idx], X[test_idx]
                y_train, y_test = y_task1[train_idx], y_task1[test_idx]
    
                # (Uses ImbPipeline internally to handle scaling then SMOTE)
                pipeline = build_nested_pipeline(model_instance)
    
                # Inner Loop: Hyperparameter Optimization
                # GridSearchCV now handles Scaling & SMOTE for every inner split
                grid = GridSearchCV(
                    pipeline,
                    param_grid,
                    scoring="roc_auc",
                    cv=inner_cv,
                    n_jobs=-1
                )
                grid.fit(X_train, y_train)
    
                # Evaluate the best model on the unseen 'outer' test fold
                best_est = grid.best_estimator_
    
                # These functions work on the pipeline (scaling/prediction)
                y_score = get_scores_for_estimator(best_est, X_test)
                y_pred = best_est.predict(X_test)
    
                # Metrics
                fold_auc.append(roc_auc_score(y_test, y_score))
                fold_recall.append(recall_score(y_test, y_pred))
                fold_spec.append(compute_specificity(y_test, y_pred))
                fold_bal.append(balanced_accuracy_score(y_test, y_pred))
    
                y_true_all.extend(y_test)
                y_score_all.extend(y_score)
    
            # Store Results
            mean_auc = np.mean(fold_auc)
            std_auc = np.std(fold_auc)
            nested_results.append({
                "FeatureFamily": family_name,
                "Model": model_name,
                "ROC_AUC_mean": mean_auc,
                "ROC_AUC_std": std_auc,
                "Stability_Score": mean_auc - std_auc, # For ranking
                "Recall_mean": np.mean(fold_recall),
                "Spec_mean": np.mean(fold_spec),
                "BalAcc_mean": np.mean(fold_bal),
            })
    
            outer_predictions[(family_name, model_name)] = {
                "y_true": np.array(y_true_all),
                "y_score": np.array(y_score_all),
                "fold_auc": np.array(fold_auc)
            }
    
        print(f"Finished Family: {family_name}")
    
    # Convert to DataFrame for ranking
    nested_results_df = pd.DataFrame(nested_results)
    
    """### Stability ranking + Heatmap"""
    
    # Stability Ranking
    ranked_df = nested_results_df.sort_values("Stability_Score", ascending=False).reset_index(drop=True)
    
    print("\n--- Top 5 Most Stable Configurations (Nested CV) ---")
    display(ranked_df.head(5)[["FeatureFamily", "Model", "ROC_AUC_mean", "ROC_AUC_std", "Stability_Score"]])
    
    pivot_stability = ranked_df.pivot(index="FeatureFamily", columns="Model", values="Stability_Score")
    
    # Order families & models for better visual flow
    fam_order = pivot_stability.max(axis=1).sort_values(ascending=False).index
    pivot_stability = pivot_stability.reindex(index=fam_order)
    
    plt.figure(figsize=(10, 6))
    sns.heatmap(
        pivot_stability,
        annot=True,
        fmt=".3f",
        cmap="magma",
        cbar_kws={"label": "Stability Score (Mean AUC - SD)"}
    )
    plt.title("Nested CV Robustness: Feature Family x Model")
    plt.show()
    
    """The fact that the low_freq family (Delta/Theta/Alpha) is the most stable suggests that the "PD Signal" is concentrated in lower frequency oscillations rather than broad-spectrum noise.
    
    
    The ranking was defined according to a Stability Score (Mean AUC - SD)
    
    
    Gradient Boosting classifier achieved the highest stability score, combining a high mean AUC with a controlled standard deviation.
    
    While the sham_band family showed high raw performance with RF , the low_freq family paired with boosting proved more resilient to subject-level variability.
    
    ## TASK 2:
    
    ### Nested CV
    """
    
    # Containers for Cog Task results
    nested_results_cog = []
    outer_predictions_cog = {}
    
    # Target for Task 2: Binary cognition
    y_task2 = y_binary
    
    print("Starting Nested CV for Cognitive Impairment...")
    
    # Iterate over RAW features
    for family_name, X in FEATURES_RAW.items():
        for model_name, model_instance in models.items():
            fold_auc, fold_recall, fold_spec, fold_bal = [], [], [], []
            y_true_all, y_score_all = [], []
    
            param_grid = build_param_grid(model_name)
    
            # Outer Loop: Generalization
            for train_idx, test_idx in outer_cv.split(X, y_task2):
                X_train, X_test = X[train_idx], X[test_idx]
                y_train, y_test = y_task2[train_idx], y_task2[test_idx]
    
                # Build pipeline (Scaler -> SMOTE -> Model)
                pipeline = build_nested_pipeline(model_instance)
    
                # Inner Loop: Optimization
                grid = GridSearchCV(
                    pipeline,
                    param_grid,
                    scoring="roc_auc",
                    cv=inner_cv,
                    n_jobs=-1
                )
                grid.fit(X_train, y_train)
    
                # Eval best model on unseen fold
                best_est = grid.best_estimator_
                y_score = get_scores_for_estimator(best_est, X_test)
                y_pred = best_est.predict(X_test)
    
                fold_auc.append(roc_auc_score(y_test, y_score))
                fold_recall.append(recall_score(y_test, y_pred))
                fold_spec.append(compute_specificity(y_test, y_pred))
                fold_bal.append(balanced_accuracy_score(y_test, y_pred))
    
                y_true_all.extend(y_test)
                y_score_all.extend(y_score)
    
            # Calculate Results
            mean_auc = np.mean(fold_auc)
            std_auc = np.std(fold_auc)
    
            nested_results_cog.append({
                "FeatureFamily": family_name,
                "Model": model_name,
                "ROC_AUC_mean": mean_auc,
                "ROC_AUC_std": std_auc,
                "Stability_Score": mean_auc - std_auc,
                "Recall_mean": np.mean(fold_recall),
                "Spec_mean": np.mean(fold_spec),
                "BalAcc_mean": np.mean(fold_bal),
            })
    
            # Save predictions for the Tiered (y_tiered) analysis
            outer_predictions_cog[(family_name, model_name)] = {
                "y_true": np.array(y_true_all),
                "y_score": np.array(y_score_all),
                "fold_auc": np.array(fold_auc),
            }
    
        print(f"Finished Family: {family_name}")
    
    nested_results_cog_df = pd.DataFrame(nested_results_cog)
    
    """### Stability ranking + Heatmap"""
    
    # Ranking
    ranked_cog_df = nested_results_cog_df.sort_values(by=["Stability_Score"], ascending=[False]).reset_index(drop=True)
    print("\n--- Top 5 Most Stable Configurations (Nested CV) ---")
    display(ranked_cog_df.head(5)[["FeatureFamily", "Model", "ROC_AUC_mean", "ROC_AUC_std", "Stability_Score"]])
    
    # Pivot for Heatmap
    pivot_stability_cog = ranked_cog_df.pivot(index="FeatureFamily", columns="Model", values="Stability_Score")
    
    # Order for readability
    fam_order_cog = pivot_stability_cog.max(axis=1).sort_values(ascending=False).index
    pivot_stability_cog = pivot_stability_cog.reindex(index=fam_order_cog)
    
    plt.figure(figsize=(10, 6))
    sns.heatmap(
        pivot_stability_cog,
        annot=True,
        fmt=".3f",
        cmap="viridis",
        cbar_kws={"label": "Stability Score (Mean AUC - SD)"}
    )
    plt.title("Cognitive Impairment Robustness (Pre-Scaled Data)")
    plt.show()
    
    """This suggests that the relationship between EEG and cognitive decline is likely nonlinear. The RBF kernel is excellent at finding complex, multi-dimensional boundaries in high-dimensional spectral data.
    
    
    ---
    
    
    This also suggests that low-frequency oscillations are the primary carrier of the neurophysiological "signal" for both motor disease and cognitive decline.
    
    Also, when comparing the Stability Scores, those corresponding to the Cognition task are visibly higher than those of the PD diagnosis.
    
    ## Graded pattern analysis (validation)
    """
    
    # Most stable cognitive model
    best_cog_row = ranked_cog_df.iloc[0]
    best_cog_key = (best_cog_row.FeatureFamily, best_cog_row.Model)
    
    # Confidence of Impairment - y_score contains the probabilities for every subject from their time in the 'outer' test fold
    cog_scores = outer_predictions_cog[best_cog_key]["y_score"]
    
    
    analysis_df = pd.DataFrame({
        "Model_Confidence": cog_scores,
        "Clinical_Tier": y_tiered
    })
    
    tier_mapping = {0: "Preserved", 1: "Standard", 2: "Impaired"}
    analysis_df["Tier_Label"] = analysis_df["Clinical_Tier"].map(tier_mapping)
    
    # Kruskal-Wallis: Non-parametric ANOVA to see if the 3 groups differ
    stat, p_val = kruskal(
        analysis_df[analysis_df["Clinical_Tier"]==0]["Model_Confidence"],
        analysis_df[analysis_df["Clinical_Tier"]==1]["Model_Confidence"],
        analysis_df[analysis_df["Clinical_Tier"]==2]["Model_Confidence"]
    )
    
    plt.figure(figsize=(10, 6))
    
    sns.violinplot(
        x="Tier_Label",
        y="Model_Confidence",
        data=analysis_df,
        order=["Preserved", "Standard", "Impaired"],
        palette="muted",
        inner="quartile",
        cut=0 # Constrain violin to the data range
    )
    
    # Overlay indiv points
    sns.stripplot(
        x="Tier_Label",
        y="Model_Confidence",
        data=analysis_df,
        order=["Preserved", "Standard", "Impaired"],
        color="black",
        alpha=0.3,
        jitter=True
    )
    
    plt.title(f"EEG Cognitive Continuum: Model Probability across Clinical Tiers\n(Kruskal-Wallis p={p_val:.4e})")
    plt.ylabel("Probability of Impairment (Model Score)")
    plt.xlabel("Clinical Assessment Tier")
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()
    
    print(f"Kruskal-Wallis Test: H-stat = {stat:.2f}, p-value = {p_val:.4e}")
    
    """## Interpretation
    
    ### Consolidated performance
    """
    
    def bootstrap_auc_ci(y_true, y_score, n_boot=1000, seed=RANDOM_STATE):
        rng = np.random.RandomState(seed)
        n = len(y_true)
        aucs = []
        for _ in range(n_boot):
            # Resample with replacement
            idx = rng.randint(0, n, n)
            # Ensure both classes are present in the bootstrap sample
            if len(np.unique(y_true[idx])) < 2:
                continue
            aucs.append(roc_auc_score(y_true[idx], y_score[idx]))
    
        aucs = np.array(aucs)
        # Standard 95% CI (2.5th to 97.5th percentile)
        ci_low, ci_high = np.percentile(aucs, [2.5, 97.5])
        return ci_low, ci_high
    
    # Winners for both tasks
    best_pd = ranked_df.iloc[0]
    best_cog = ranked_cog_df.iloc[0]
    
    summary_data = []
    
    # T1
    key_pd = (best_pd.FeatureFamily, best_pd.Model)
    y_true_pd = outer_predictions[key_pd]["y_true"]
    y_score_pd = outer_predictions[key_pd]["y_score"]
    ci_low_pd, ci_high_pd = bootstrap_auc_ci(y_true_pd, y_score_pd)
    
    summary_data.append({
        "Clinical Task": "PD vs. HC",
        "Best Feature Family": best_pd.FeatureFamily,
        "Best Model": best_pd.Model,
        "Mean AUC": f"{best_pd.ROC_AUC_mean:.3f}",
        "95% CI": f"[{ci_low_pd:.3f}, {ci_high_pd:.3f}]",
        "Stability": f"{best_pd.Stability_Score:.3f}",
        "Recall": f"{best_pd.Recall_mean:.3f}",
        "Spec.": f"{best_pd.Spec_mean:.3f}"
    })
    
    # T2
    key_cog = (best_cog.FeatureFamily, best_cog.Model)
    y_true_cog = outer_predictions_cog[key_cog]["y_true"]
    y_score_cog = outer_predictions_cog[key_cog]["y_score"]
    ci_low_cog, ci_high_cog = bootstrap_auc_ci(y_true_cog, y_score_cog)
    
    summary_data.append({
        "Clinical Task": "Cognition (Binary)",
        "Best Feature Family": best_cog.FeatureFamily,
        "Best Model": best_cog.Model,
        "Mean AUC": f"{best_cog.ROC_AUC_mean:.3f}",
        "95% CI": f"[{ci_low_cog:.3f}, {ci_high_cog:.3f}]",
        "Stability": f"{best_cog.Stability_Score:.3f}",
        "Recall": f"{best_cog.Recall_mean:.3f}",
        "Spec.": f"{best_cog.Spec_mean:.3f}"
    })
    
    final_summary_table = pd.DataFrame(summary_data)
    
    # Display formatted for easy copy-pasting into your report
    print("\nCONSOLIDATED SUPERVISED PERFORMANCE")
    display(final_summary_table)
    
    """### Feature Importances"""
    
    X_best_pd = FEATURES_RAW[best_pd.FeatureFamily]
    y_pd_task = np.where(y_diag == "PD", 1, 0)
    X_best_cog = FEATURES_RAW[best_cog.FeatureFamily]
    
    def plot_top_features_fixed(family_name, model_name, X, y, task_title):
        # 1. Re-train best model on full task data using the pipeline
        pipeline = build_nested_pipeline(models[model_name])
        pipeline.fit(X, y)
        model_step = pipeline.named_steps['model']
    
        # 2. Extract importance
        if hasattr(model_step, 'feature_importances_'):
            importances = model_step.feature_importances_
        elif hasattr(model_step, 'coef_'):
            importances = np.abs(model_step.coef_[0])
        else:
            from sklearn.inspection import permutation_importance
            print(f"Calculating Permutation Importance for {model_name} on {task_title}...")
            result = permutation_importance(
                pipeline, X, y, n_repeats=10, random_state=RANDOM_STATE, n_jobs=-1, scoring='roc_auc'
            )
            importances = result.importances_mean
    
        # 3. Dynamic Name Reconstruction
        channels = utils.SELECTED_CHANNELS
    
        if family_name == "low_freq":
            # 24 Band Powers + 8 TARs + 1 Global
            names = [f"{ch}_{b}" for ch in channels for b in ['delta', 'theta', 'alpha']]
            names += [f"{ch}_TAR" for ch in channels]
            names += ["Global_TAR"]
        elif family_name == "sham_band":
            # 32 Band Powers (4 per channel)
            names = [f"{ch}_{b}" for ch in channels for b in ['delta', 'theta', 'alpha', 'beta']]
        else:
            # Fallback for full_psd (Freq Bins)
            names = [f"Bin_{i}" for i in range(X.shape[1])]
    
        # 4. Sort and plot top 10
        indices = np.argsort(importances)[-10:]
        top_importances = importances[indices]
        top_names = [names[i] for i in indices]
    
        plt.figure(figsize=(10, 6))
        plt.barh(range(len(indices)), top_importances, align='center', color='#2c3e50')
        plt.yticks(range(len(indices)), top_names)
        plt.title(f"Top 10 Drivers: {task_title}\n({family_name} + {model_name})", fontsize=14)
        plt.xlabel("Importance Score (Contribution to AUC)")
        plt.grid(axis='x', linestyle='--', alpha=0.7)
        plt.tight_layout()
        plt.show()
    
    plot_top_features_fixed(best_pd.FeatureFamily, best_pd.Model, X_best_pd, y_pd_task, "PD vs. HC")
    plot_top_features_fixed(best_cog.FeatureFamily, best_cog.Model, X_best_cog, y_binary, "Cognitive Impairment")
    
    """For PD diagnosis (PD vs. HC), the Gradient Boosting model was overwhelmingly driven by posterior low-frequency power. The top driver, PO7_Theta (Importance: 0.156), along with PO7_TAR and O2_Theta, indicates that the early hallmarks of PD are most visible in the occipito-parietal region.
    
    
    In the cognitive task, the feature landscape shifts toward frontal involvement and higher frequency bands. While O2_theta remains a factor, we see the emergence of F3_alpha (rank 2) and F4_alpha (rank 4). More importantly, three of the top six drivers are Beta-band features (O2_beta, C3_beta, P4_beta).
    
    
    """
    
    plot_top_features_fixed("low_freq", "LogisticRegression", FEATURES_RAW["low_freq"], y_binary, "Cognitive Impairment")
    
    """To ensure clinical interpretability, we examined the top drivers of both the champion (sham_band) and the runner-up (low_freq) models for Task 2. While the sham_band identified auxiliary beta-band markers, the low_freq Logistic Regression model (Stability: 0.747) confirmed that the C4_TAR (Importance: 1.26) and F3_alpha were the primary determinants of cognitive classification. This secondary analysis provides crucial cross-validation, aligning our supervised results with the TAR-dominant phenotypes identified in the unsupervised clustering
    
    #### Table visualization
    """
    
    def get_feature_importance_table(family_name, model_name, X, y):
        # 1. Re-train the pipeline on the specific RAW feature set
        pipeline = build_nested_pipeline(models[model_name])
        pipeline.fit(X, y)
        model_step = pipeline.named_steps['model']
    
        # 2. Extract importance based on model type
        if hasattr(model_step, 'feature_importances_'):
            importances = model_step.feature_importances_
        elif hasattr(model_step, 'coef_'):
            importances = np.abs(model_step.coef_[0])
        else:
            from sklearn.inspection import permutation_importance
            # Use scoring='roc_auc' to align with CV metric
            result = permutation_importance(pipeline, X, y, n_repeats=10,
                                            random_state=RANDOM_STATE, n_jobs=-1, scoring='roc_auc')
            importances = result.importances_mean
    
        # 3. Dynamic Name Reconstruction to match the feature matrix shape
        channel_list = utils.SELECTED_CHANNELS
    
        if family_name == "low_freq":
            # Bands (24) + TARs (8) + Global (1) = 33
            names = [f"{ch}_{b}" for ch in channel_list for b in ['delta', 'theta', 'alpha']]
            names += [f"{ch}_TAR" for ch in channel_list]
            names += ["Global_TAR"]
        elif family_name == "sham_band":
            # 4 Bands per channel = 32
            names = [f"{ch}_{b}" for ch in channel_list for b in ['delta', 'theta', 'alpha', 'beta']]
        else:
            # Fallback for full_psd or unexpected shapes
            names = [f"feat_{i}" for i in range(X.shape[1])]
    
        # 4. Final safety check: ensure lengths match before creating the DataFrame
        if len(names) != len(importances):
            # If there's still a mismatch, fallback to generic naming so it doesn't crash
            names = [f"Feature_{i}" for i in range(len(importances))]
    
        df_imp = pd.DataFrame({
            'Feature': names,
            'Importance': importances
        }).sort_values(by='Importance', ascending=False).reset_index(drop=True)
    
        return df_imp.head(10)
    
    # Execute
    print(f"\nTABLE: Top 10 Drivers for Diagnosis ({best_pd.FeatureFamily})")
    display(get_feature_importance_table(best_pd.FeatureFamily, best_pd.Model, X_best_pd, y_pd_task))
    print(f"\nTABLE: Top 10 Drivers for Cognition ({best_cog.FeatureFamily})")
    display(get_feature_importance_table(best_cog.FeatureFamily, best_cog.Model, X_best_cog, y_binary))
    print(f"\nTABLE: Top 10 Drivers for runner up Cognition ({"low_freq"})")
    display(get_feature_importance_table("low_freq", "LogisticRegression", FEATURES_RAW["low_freq"], y_binary))
    
    """## Holdout evaluation"""
    
    """ ### Task 1"""
    
    def run_holdout_evaluation(X, y, model_name, task_title, labels=['Control', 'PD']):
        # Split
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, stratify=y, random_state=RANDOM_STATE
        )
    
        # Fit
        pipeline = build_nested_pipeline(models[model_name])
        pipeline.fit(X_train, y_train)
    
        # Predict
        y_probs = get_scores_for_estimator(pipeline, X_test)
        y_pred = pipeline.predict(X_test)
    
        fig, ax = plt.subplots(1, 2, figsize=(14, 5))
    
        # ROC Curve
        fpr, tpr, _ = roc_curve(y_test, y_probs)
        ax[0].plot(fpr, tpr, label=f'AUC = {auc(fpr, tpr):.2f}', color='teal', lw=3)
        ax[0].plot([0, 1], [0, 1], color='gray', linestyle='--')
        ax[0].set_title(f'ROC Curve: {task_title}', fontsize=14)
        ax[0].set_xlabel('False Positive Rate')
        ax[0].set_ylabel('True Positive Rate')
        ax[0].legend(loc="lower right")
    
        # Confusion Matrix
        cm = confusion_matrix(y_test, y_pred)
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False, ax=ax[1],
                    xticklabels=labels, yticklabels=labels)
        ax[1].set_title(f'Confusion Matrix: {task_title}', fontsize=14)
        ax[1].set_ylabel('Actual Label')
        ax[1].set_xlabel('Predicted Label')
    
        plt.tight_layout()
        plt.show()
    
        return pipeline
    
    # Task 1
    final_pd_model = run_holdout_evaluation(
        FEATURES_RAW[best_pd.FeatureFamily], y_task1, best_pd.Model, "PD Diagnosis"
    )
    
    """**Sensitivity/Recall:** We are catching $61\%$ of PD patients ($11/18$)."""
    """**Specificity:** We are correctly identifying $55\%$ of Controls ($5/9$)."""
    """The model is leaning toward "PD" (11 true positives vs 7 false negatives)."""
    
    """### Task 2"""
    
    # 1. Split indices using RAW data
    idx_train, idx_test = train_test_split(
        np.arange(len(y_binary)), test_size=0.2, stratify=y_binary, random_state=RANDOM_STATE
    )
    
    # Extract RAW Features for training scaling is handled internally in the pipeline
    X_train_cog = FEATURES_RAW[best_cog.FeatureFamily][idx_train]
    y_train_cog = y_binary[idx_train]
    
    # Build Pipeline (Scaler + SMOTE + RBFSVM)
    final_cog_model = build_nested_pipeline(models[best_cog.Model])
    final_cog_model.fit(X_train_cog, y_train_cog)
    
    # Predict on  Test set
    X_test_cog = FEATURES_RAW[best_cog.FeatureFamily][idx_test]
    y_test_tiers = y_tiered[idx_test]
    y_test_binary = y_binary[idx_test]
    
    # The pipeline automatically applies the training-set scaling to X_test_cog
    y_pred_cog = final_cog_model.predict(X_test_cog)
    
    def run_task2_final_visuals(model, X_test, y_binary_test, y_tiered_test):
        # Get Predictions & Probs
        y_probs = get_scores_for_estimator(model, X_test)
        y_pred = model.predict(X_test)
    
        fig, ax = plt.subplots(1, 3, figsize=(18, 5))
    
        # ROC CURVE
        fpr, tpr, _ = roc_curve(y_binary_test, y_probs)
        ax[0].plot(fpr, tpr, label=f'AUC = {auc(fpr, tpr):.2f}', color='teal', lw=3)
        ax[0].plot([0, 1], [0, 1], color='gray', linestyle='--')
        ax[0].set_title('ROC Curve: Cognition (Binary)', fontsize=14)
        ax[0].set_xlabel('False Positive Rate')
        ax[0].set_ylabel('True Positive Rate')
        ax[0].legend(loc="lower right")
    
        # BINARY CONFUSION MATRIX
        cm_bin = confusion_matrix(y_binary_test, y_pred)
        sns.heatmap(cm_bin, annot=True, fmt='d', cmap='Blues', cbar=False, ax=ax[1],
                    xticklabels=['Pres/Std', 'Impaired'],
                    yticklabels=['Pres/Std', 'Impaired'])
        ax[1].set_title('Confusion Matrix: Binary Task', fontsize=14)
        ax[1].set_ylabel('Actual (Binary)')
        ax[1].set_xlabel('Predicted')
    
        # TIERED CONTINUUM MATRIX
        # We use y_tiered_test (0,1,2) but model only predicts (0,1)
        cm_tier = confusion_matrix(y_tiered_test, y_pred, labels=[0, 1, 2])
        # Slice the matrix to 3 rows by 2 cols
        cm_tier_display = cm_tier[:, [0, 1]]
    
        sns.heatmap(cm_tier_display, annot=True, fmt='d', cmap='YlGnBu', cbar=False, ax=ax[2],
                    xticklabels=['Pred: Preserved', 'Pred: Impaired'],
                    yticklabels=['Actual: Preserved (0)', 'Actual: Standard (1)', 'Actual: Impaired (2)'])
        ax[2].set_title('Confusion Matrix: Tiered Continuum', fontsize=14)
        ax[2].set_ylabel('Clinical Tier (Truth)')
        ax[2].set_xlabel('Model Decision')
    
        plt.tight_layout()
        plt.show()
    
    run_task2_final_visuals(final_cog_model, X_test_cog, y_binary[idx_test], y_test_tiers)
    
    """## Shuffling"""
    
    """### Definitions"""
    
    def run_validity_test(X, y, model, n_permutations=100, mode='labels'):
        # mode='labels': Standard permutation test (shuffles y)
        # mode='features': Frequency/Feature shuffling (shuffles X columns independently)
    
        null_aucs = []
        print(f"Running {n_permutations} permutations in [{mode}] mode...")
    
        cv_simple = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
        pipeline = build_nested_pipeline(model)
    
        X_work = X.copy()
        y_work = y.copy()
    
        for i in range(n_permutations):
            if mode == 'labels':
                # Label Shuffling
                np.random.shuffle(y_work)
            elif mode == 'features':
                # Frequency Shuffling - shuffles each col independently to break the corr structure between EEG bands
                for col in range(X_work.shape[1]):
                    np.random.shuffle(X_work[:, col])
    
            scores = cross_validate(
                pipeline, X_work, y_work,
                cv=cv_simple,
                scoring='roc_auc',
                n_jobs=-1
            )
            null_aucs.append(np.mean(scores['test_score']))
    
            if (i + 1) % 25 == 0:
                print(f"  {i + 1}/{n_permutations} complete...")
    
        return np.array(null_aucs)
    
    def plot_validity_results(original_auc, label_null, feature_null, task_name):
        plt.figure(figsize=(12, 6))
    
        sns.kdeplot(label_null, fill=True, color="gray", label="Label Shuffle (Null)", alpha=0.5)
        sns.kdeplot(feature_null, fill=True, color="blue", label="Feature Shuffle (Null)", alpha=0.3)
    
        # Actual performance
        plt.axvline(original_auc, color="red", linestyle="--", lw=2, label=f"Original AUC ({original_auc:.3f})")
    
        plt.title(f"Robustness Check: {task_name}", fontsize=15)
        plt.xlabel("ROC AUC Score", fontsize=12)
        plt.ylabel("Density", fontsize=12)
        plt.xlim(0.3, 0.9) # Focus on the relevant range
        plt.legend(loc="upper left")
    
        # p-val
        p_val = (np.sum(label_null >= original_auc) + 1) / (len(label_null) + 1)
        plt.annotate(f"p < {p_val:.4f}", xy=(original_auc, 0.5), xytext=(original_auc+0.05, 1.5),
                     arrowprops=dict(facecolor='black', shrink=0.05), fontsize=12, fontweight='bold')
    
        plt.tight_layout()
        plt.show()
    
    """### Task 1"""
    
    # Label shuffle (p-val test)
    label_null = run_validity_test(FEATURES_RAW[best_pd.FeatureFamily], y_task1, models[best_pd.Model], mode='labels')
    
    # Feature/Frequency Shuffle (Data integrity test)
    feature_null = run_validity_test(FEATURES_RAW[best_pd.FeatureFamily], y_task1, models[best_pd.Model], mode='features')
    
    # Quantify Performance Drop
    original_auc = float(final_summary_table[final_summary_table['Clinical Task'] == "PD vs. HC"]["Mean AUC"].iloc[0]) # From results
    drop_labels = original_auc - np.mean(label_null)
    drop_features = original_auc - np.mean(feature_null)
    
    print(f"\nVALIDITY RESULTS:")
    print(f"Original AUC: {original_auc:.4f}")
    print(f"Label Shuffle Null Mean: {np.mean(label_null):.4f} (Drop: {drop_labels:.4f})")
    print(f"Feature Shuffle Null Mean: {np.mean(feature_null):.4f} (Drop: {drop_features:.4f})")
    
    """A drop of ~0.26 in AUC when shuffling either the labels or the features is a massive delta. It proves that the  model isnt just getting lucky with the data, it is specifically tuned to the relationship between those EEG features and the clinical diagnosis. Since the null means are nearly 0.50 (pure random chance), we can confidently state that the original 0.765 AUC is derived entirely from genuine neurophysiological patterns."""
    
    plot_validity_results(original_auc, label_null, feature_null, "Task 1: PD Diagnosis")
    
    """### Task 2"""
    
    # Label shuffle (p-val test)
    label_null_cog = run_validity_test(FEATURES_RAW[best_cog.FeatureFamily], y_binary, models[best_cog.Model], mode='labels')
    
    # Feature/Frequency Shuffle (Data integrity test)
    feature_null_cog = run_validity_test(FEATURES_RAW[best_cog.FeatureFamily], y_binary, models[best_cog.Model], mode='features')
    
    # Quantify Performance Drop
    original_auc_cog = float(final_summary_table[final_summary_table['Clinical Task'] == "Cognition (Binary)"]["Mean AUC"].iloc[0]) # From results
    drop_labels_cog = original_auc_cog - np.mean(label_null_cog)
    drop_features_cog = original_auc_cog - np.mean(feature_null_cog)
    
    print(f"\nVALIDITY RESULTS: TASK 2 (COGNITION)")
    print(f"Original AUC: {original_auc_cog:.4f}")
    print(f"Label Shuffle Null Mean: {np.mean(label_null_cog):.4f} (Drop: {drop_labels_cog:.4f})")
    print(f"Feature Shuffle Null Mean: {np.mean(feature_null_cog):.4f} (Drop: {drop_features_cog:.4f})")
    
    plot_validity_results(original_auc_cog, label_null_cog, feature_null_cog, "Task 2: Cognitive Impairment")
    
    print("Supervised analysis complete.")
