def run_unsupervised(): 
    print("Running unsupervised pipeline...")

    """unsupervised.ipynb
    
    Automatically generated by Colab.
    
    Original file is located at
        https://colab.research.google.com/drive/1U5hrwR6z9EpjwMFBS3ZGG5We0D6wSjTN
    
    # **ML PROJECT - EEG PD**
    ## Imports & Configuration
    """
    
    import os
    import warnings
    import copy
    warnings.filterwarnings("ignore", category=RuntimeWarning)
    
    import numpy as np
    import pandas as pd
    from tqdm import tqdm
    
    import matplotlib.pyplot as plt
    import seaborn as sns
    import plotly.express as px
    from matplotlib.lines import Line2D
    
    from scipy.stats import mode, pearsonr, entropy, pointbiserialr, zscore
    import scipy.stats as stats
    from scipy.spatial import ConvexHull
    from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
    from scipy.spatial.distance import pdist, squareform
    from sklearn.linear_model import LinearRegression
    from sklearn.manifold import TSNE
    from scipy.integrate import trapezoid
    from scipy.signal import spectrogram
    
    import mne
    from mne.time_frequency import psd_array_welch
    from sklearn.neighbors import NearestNeighbors
    from random import sample
    
    from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
    from sklearn.decomposition import PCA
    import umap
    from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
    from sklearn.mixture import GaussianMixture
    from sklearn.metrics import (
    	silhouette_score, davies_bouldin_score, calinski_harabasz_score,
    	adjusted_rand_score, normalized_mutual_info_score, f1_score, confusion_matrix, ConfusionMatrixDisplay,
    	classification_report, accuracy_score, roc_curve, auc, roc_auc_score, make_scorer, balanced_accuracy_score
    )
    from sklearn.model_selection import StratifiedKFold, train_test_split, cross_val_score, GroupKFold, cross_validate, GroupShuffleSplit
    from sklearn.ensemble import RandomForestClassifier, IsolationForest
    from sklearn.svm import SVC
    
    import sys
    from pathlib import Path
    
    # Detect Colab
    IN_COLAB = "google.colab" in sys.modules
    
    if IN_COLAB:
        from google.colab import drive
        drive.mount("/content/drive")  # Mount Drive first
    
        # Path to your project folder in Drive
        PROJECT_ROOT = Path("/content/drive/MyDrive/ML_RS_EEG")
    
        # Make sure Python can find utils.py
        sys.path.append(str(PROJECT_ROOT))
    
    else:
        # Local machine
        PROJECT_ROOT = Path.cwd()
        sys.path.append(str(PROJECT_ROOT))
    
    import utils
    
    plt.ioff()
    RANDOM_STATE = utils.RANDOM_STATE
    
    PROJECT_ROOT, DATA_ROOT, csv_path = utils.setup_environment()
    
    """All models are fixed with a random seed to ensure reproducibility. Importantly, the analysis deliberately relies on **multiple clustering algorithms and dimensionality reduction techniques** to avoid conclusions driven by a single method.
    
    # 1. DATASET DISCOVERY & SANITY CHECKS
    
    The dataset consists of **resting-state EEG recordings** from Parkinson’s disease patients and healthy controls. The overarching goal of the unsupervised analysis is **not classification**, but rather to characterize the **intrinsic geometry** of EEG feature space.
    
    ## Sanity checks
    """
    
    raw_csv = pd.read_csv(csv_path)
    
    set_files = sorted(DATA_ROOT.glob("sub-*/eeg/*.set"))
    
    print(f"Subjects found: {len(set_files)}")
    print(f"First 3 EEG files: {set_files[:3]}")
    
    # Load one example recording (sanity check only)
    example_file = set_files[0]
    raw = mne.io.read_raw_eeglab(example_file, preload=False, verbose=False)
    
    print("Sampling frequency:", raw.info["sfreq"])
    print("Number of channels:", len(raw.ch_names))
    print("Duration (seconds):", raw.n_times / raw.info["sfreq"])
    print("First 10 channel names:", raw.ch_names[:10])
    
    # Visual inspection (not used later)
    raw.plot(n_channels=20, start=10, duration=10, scalings="auto")
    raw.plot_sensors(show_names=True)
    
    psd = raw.compute_psd(method="welch", fmin=0.5, fmax=50, verbose=False)
    psd.plot(dB=True)
    
    """## Participants, labels and cognitive scores
    
    We ask whether latent structure emerges naturally from the data, and if so, whether this structure aligns with disease diagnosis or clinical variables such as age, cognition (MOCA), or motor severity (UPDRS).
    """
    
    cognitive_cols = ['NIH FICAT', 'NIH DCCST', 'NIH PCPST', 'NIH PSMT','NIH PVT']
    
    # Keep only rows where all cognitive tests are not NaN
    participants, set_files, valid_subjects = utils.sync_eeg_and_metadata(raw_csv, DATA_ROOT)
    
    print(participants["GROUP"].value_counts())
    
    age = participants.loc[participants["participant_id"].isin([f.parts[-3] for f in set_files]),"AGE"].values
    moca = participants.loc[participants["participant_id"].isin([f.parts[-3] for f in set_files]),"MOCA"].values
    updrs = participants.loc[participants["participant_id"].isin([f.parts[-3] for f in set_files]),"UPDRS"].values
    nih_ficat = participants.loc[participants["participant_id"].isin([f.parts[-3] for f in set_files]),"NIH FICAT"].values
    
    
    # Sanity check
    if len(age) == len(valid_subjects):
      print("AGE vector shape:", age.shape)
    else:
      raise ValueError("AGE vector length mismatch")
    
    y_true = participants.set_index("participant_id").loc[valid_subjects, "GROUP"].values
    
    """Labels are loaded here for bookkeeping and post hoc evaluation only.
    They are not used in feature construction or clustering.
    """
    
    subject_info = participants.copy()
    sns.pairplot(subject_info[['AGE', 'MOCA', 'UPDRS', 'NIH FICAT', 'NIH DCCST', 'NIH PCPST', 'NIH PSMT','NIH PVT','GROUP']], hue="GROUP", palette={"PD":'Red' , "Control": 'Blue'})
    
    plt.show()
    
    """## Common channels"""
    
    def load_eeg(file_path: Path) -> mne.io.Raw:
      # Load using mne
      return mne.io.read_raw_eeglab(
        file_path,
        preload=True,
        verbose=False
      )
    
    # Determine common channel set (intersection across subjects)
    common_channels = utils.get_common_channels(set_files)
    print(f"There are {len(common_channels)} channels common to all {len(set_files)} subjects.")
    
    print(utils.SELECTED_CHANNELS)
    
    """## Domain specific cognitive score + Processing"""
    
    # Check how well the NIH scores correlate with each other
    internal_corr = participants[cognitive_cols].corr()
    
    sns.heatmap(internal_corr, annot=True, cmap='viridis')
    plt.title("Internal Correlation of Cognitive Domains")
    plt.show()
    
    """FICAT, DCCST, and PCPST are all strongly inter-correlated ($0.45$ to $0.55$). These three tests (Inhibitory Control, Cognitive Flexibility, and Processing Speed) are clearly moving together. They represent a "Frontal-Executive" core.PSMT and PVT have much weaker ties to that core (dropping as low as $0.18$). These measure Memory and Vocabulary/Vision, which are likely being preserved or affected differently in the group."""
    
    # Z-scores for EVERYONE based on Control Norms
    participants = utils.get_processed_participants(participants)
    
    print(f"-  CLINICAL LABEL SUMMARY (N={len(participants)})  -")
    print("\nGroup Breakdown of Tiers (0=Preserved, 1=Standard, 2=Impaired):")
    print(participants.groupby('GROUP')['cog_tier'].value_counts().unstack().fillna(0).astype(int))
    
    print()
    print("Binary Distribution (1=Impaired, 0=Not_Impaired):")
    binary_counts = participants.groupby('GROUP')['cog_binary'].value_counts().unstack().fillna(0).astype(int)
    binary_counts.columns = ['Not_Impaired (0)', 'Impaired (1)']
    print(binary_counts)
    
    """To establish a biologically grounded ground-truth for cognitive status, participants were categorized using a normative-referenced composite score targeting the executive fuction domain. Recognizing that Inhibitory Control (FICAT), Cognitive Flexibility (DCCST), and Processing Speed (PCPST) exhibited strong inter-correlation ($r = 0.45$ to $0.55$), an Executive Composite was calculated. This was achieved by transforming raw scores into Z-scores based exclusively on the distribution of the Healthy Control cohort ($N=46$). By using the healthy population as the baseline yardstick, we ensured that "Impairment" was defined not by arbitrary clusters, but by significant deviation from neurotypical performance. Specifically, a threshold of $Z < -1.0$ (representing the bottom 15% of healthy performance) was used to define Clinical Impairment (Tier 0), while $Z \ge 0$ identified Preserved function (Tier 2). This rigorous stratification provides a stable clinical anchor for the subsequent unsupervised EEG clustering, allowing us to test whether natural brain-wave patterns respect these established clinical boundaries.
    
    # 2. CORE PROCESSING UTILITIES + FEATURE CONSTRUCTION
    
    ## Feature construction
    
    Multiple feature representations are constructed to probe EEG structure at different levels of abstraction. This includes high-dimensional spectral representations as well as biologically motivated low-frequency summaries. Importantly, features are constructed **per channel × band**, preserving spatial information and enabling interpretability of latent axes.
    
    If we focus on known PD-sensitive frequencies, does diagnostic separation improve?
    Prior work identified the 0.5–12 Hz range as maximally discriminative between PD and control subjects, spanning delta, theta, and low-alpha bands known to be abnormal in PD.
    
    LEAPD bandpower features were included as a hypothesis-driven, disease-optimized representation, complementary to generic spectral features. This allows us to assess whether unsupervised structure aligns more strongly with PD-specific spectral abnormalities or emerges independently of disease-informed feature design.
    """
    
    FEATURES = utils.construct_master_features(set_files, utils.SELECTED_CHANNELS)
    
    print()
    print("-  FINAL INTEGRITY CHECK  -")
    for key, data in FEATURES.items():
      print(f"Set: {key} | Shape: {data.shape}")
    
    profile_cols = utils.get_feature_names()
    # Verify the length matches data columns (Should be 33)
    print(f"Total Features: {len(profile_cols)}")
    
    """Sizes ok:
    
    low_freq = $(8 \text{ channels} \times 3 \text{ bands}) + 8 \text{ per-channel TARs} + 1 \text{ Global TAR} = \mathbf{33}$
    
    sham_band =  $(8 \text{ channels} \times 4 \text{ bands}) $ = 32
    
    ## Outlier Id
    """
    
    subs_list, outlier_ids, participants = utils.clean_outliers(FEATURES, valid_subjects, participants, random_state=utils.RANDOM_STATE)
    
    print(f"--- CLEANING COMPLETE ---")
    print(f"Removed: {len(outlier_ids)} subjects: {outlier_ids} ")
    print(f"New total N: {len(participants)} (PD: {sum(participants['GROUP']=='PD')}, Control: {sum(participants['GROUP']=='Control')})")
    
    """## Feature Engineering & Normalization"""
    
    FEATURES_SCALED, y_binary, y_tiered, y_diag = utils.prepare_staged_data(FEATURES, participants, subs_list)
    
    """# UNSUPERVISED LEARNING
    ALIGNMENT ANALYSIS
    Do clusters naturally form around PD status or Cognition?
    
    ## Dim reduction tSNE
    """
    
    def diagnostic_pca_report(FEATURES_SCALED):
      pca_results = {}
    
      for name, X in FEATURES_SCALED.items():
        pca = PCA(random_state=RANDOM_STATE)
        pca.fit(X)
    
        # Calculate how many components to reach 90% variance
        cumulative_variance = np.cumsum(pca.explained_variance_ratio_)
        n_90 = np.where(cumulative_variance >= 0.90)[0][0] + 1
    
        pca_results[name] = {
          "Total Features": X.shape[1],
          "Components for 90% Var": n_90,
          "Top 3 Variance": np.sum(pca.explained_variance_ratio_[:3])
        }
    
        # Optional: Print the report
        print(f"-  PCA Report: {name}  -")
        print(f"90% of variance is captured by {n_90} components")
        print(f"The first 3 components explain {pca_results[name]['Top 3 Variance']*100:.1f}% of data\n")
    
      return pd.DataFrame(pca_results).T
    
    pca_report = diagnostic_pca_report(FEATURES_SCALED)
    print(pca_report)
    
    """The first 3 components of the feature construction based off the lower bands explain the most variance amongst the different constructions."""
    
    def plot_tsne_comparison(FEATURES_SCALED, participants_df, subs_list, color_col = 'cog_binary'):
      fig, axes = plt.subplots(1, 3, figsize=(20, 6))
    
      df_idx = participants_df.set_index("participant_id").loc[subs_list]
      color_label = df_idx[color_col]
    
      for i, (name, X) in enumerate(FEATURES_SCALED.items()):
        # Perplexity ~30
        tsne = TSNE(n_components=2, perplexity=30, random_state=RANDOM_STATE, init='pca', learning_rate='auto')
        X_embedded = tsne.fit_transform(X)
    
        sns.scatterplot(
          x=X_embedded[:, 0], y=X_embedded[:, 1],
          hue=color_label, palette='viridis', ax=axes[i], s=60
        )
        axes[i].set_title(f"t-SNE: {name}")
        axes[i].set_xlabel("Dimension 1")
        axes[i].set_ylabel("Dimension 2")
    
      plt.tight_layout()
      plt.show()
    
    plot_tsne_comparison(FEATURES_SCALED, participants, subs_list, 'cog_binary')
    
    plot_tsne_comparison(FEATURES_SCALED, participants, subs_list, 'cog_tier')
    
    plot_tsne_comparison(FEATURES_SCALED, participants, subs_list, 'GROUP')
    
    rates = [50, 200, 500]
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    
    for i, lr in enumerate(rates):
      tsne = TSNE(n_components=2, learning_rate=lr, perplexity=30, init='random', random_state=RANDOM_STATE)
      X_emb = tsne.fit_transform(FEATURES_SCALED['low_freq'])
    
      axes[i].scatter(X_emb[:, 0], X_emb[:, 1], c=participants['cog_binary'], cmap='coolwarm')
      axes[i].set_title(f"Learning Rate: {lr}")
    
    plt.show()
    
    def audit_tsne_shape(X_tsne, labels):
      # Clean labels
      labels_arr = np.array(labels).flatten()
    
      # Silhouette (Global Tightness)
      sil = silhouette_score(X_tsne, labels_arr)
    
      # KNN (Neighborhood Purity)
      knn = NearestNeighbors(n_neighbors=6)
      knn.fit(X_tsne)
    
      distances, indices = knn.kneighbors(X_tsne)
    
      # Lables 5 closest neighbors
      neighbor_labels = labels_arr[indices[:, 1:]]
    
      # Check where neighbor labels match the point label
      matches = (neighbor_labels == labels_arr[:, np.newaxis]).sum(axis=1)
      purity = matches.mean() / 5.0
    
      print(f"-  t-SNE Shape Audit  -")
      print(f"Silhouette Score: {sil:.4f}")
      print(f"Neighborhood Purity: {purity:.4f}")
    
      return sil, purity
    
    # Coords
    tsne_model = TSNE(n_components=2, perplexity=30, learning_rate='auto', init='pca', random_state=RANDOM_STATE)
    
    # Scaled features from best set (low_freq)
    X_coords = tsne_model.fit_transform(FEATURES_SCALED['low_freq'])
    
    # Labeñls
    y_audit = participants.set_index('participant_id').loc[subs_list, 'cog_binary']
    
    audit_tsne_shape(X_coords, y_audit)
    
    """The t-SNE visualization of the low-frequency features yields a Neighborhood Purity of 65%, indicating that even within a complex clinical landscape, participants tend to cluster with others sharing the same cognitive status significantly above chance levels (50%). While the Silhouette Score (0.07) is low, this is characteristic of neurophysiological data where cognitive decline exists as a biological continuum rather than discrete, isolated 'islands.' The audit confirms that while the global separation is subtle, the local manifold preserves meaningful clinical structures, justifying the use of density-based or hierarchical clustering methods to capture these groups."""
    
    audit_tsne_shape(X_coords, participants.set_index('participant_id').loc[subs_list, 'cog_tier'])
    
    """The t-SNE audit for the three-tiered cognitive classification (Preserved, Standard, Impaired) yielded a negative Silhouette Score (-0.04) and a Neighborhood Purity (around 40%) only marginally above the chance level of 1/3. This suggests that while the low-frequency EEG features carry a strong binary signal for impairment, the neurophysiological transition between 'Preserved' and 'Standard' cognitive states is highly overlapping, at least for t-SNE
    
    ## Geometric Analysis of feature constructions
    """
    
    def analyze_cluster_geometry(feature_matrix, n_clusters_range=range(2, 6)):
      scaler = StandardScaler()
      X_scaled = scaler.fit_transform(feature_matrix)
    
      # PCA to retain 90% variance to reduce noise for geometry
      pca = PCA(n_components=0.90, random_state=RANDOM_STATE)
      X_pca = pca.fit_transform(X_scaled)
    
      geo_results = []
    
      for k in n_clusters_range:
        clusterer = AgglomerativeClustering(n_clusters=k, linkage='ward')
        labels = clusterer.fit_predict(X_pca)
    
        sil = silhouette_score(X_pca, labels)
        ch = calinski_harabasz_score(X_pca, labels)
        db = davies_bouldin_score(X_pca, labels)
    
        geo_results.append({
          "k": k,
          "Silhouette": sil,
          "Calinski-Harabasz": ch,
          "Davies-Bouldin": db
        })
    
      return pd.DataFrame(geo_results)
    
    def hopkins_statistic(X):
        np.random.seed(RANDOM_STATE)
    
        d = X.shape[1]
        n = len(X)
        m = int(0.1 * n)
        nbrs = NearestNeighbors(n_neighbors=1).fit(X)
    
        # Random points in the same space (Deterministic because of np.random.seed)
        rand_X = np.random.uniform(X.min(axis=0), X.max(axis=0), (m, d))
    
        # Real points sampled
        indices = np.random.choice(range(n), m, replace=False)
        real_X = X[indices]
    
        u_dist = nbrs.kneighbors(rand_X, return_distance=True)[0]
        w_dist = nbrs.kneighbors(real_X, n_neighbors=2, return_distance=True)[0][:, 1]
    
        return [sum(u_dist) / (sum(u_dist) + sum(w_dist))]
    
    constructions = {
      "Low-Freq": FEATURES["low_freq"],
      "Sham": FEATURES["sham_band"],
      "Full PSD": FEATURES["full_psd"]
    }
    
    for name, data in constructions.items():
      h_stat = hopkins_statistic(StandardScaler().fit_transform(data))
      geo_df = analyze_cluster_geometry(data)
    
      print()
      print(f"-  Geometry Analysis: {name}")
      print(f"Hopkins Statistic: {h_stat[0].item():.4f}")
      print(geo_df)
    
    """Following the removal of multivariate outliers and the implementation of normative-adjusted labeling, the geometric analysis reveals a robust clustering tendency across all feature sets, with the Full PSD set demonstrating the least favorable profile for unsupervised discovery. The high Hopkins Statistic for the Low-Freq features significantly exceeds the 0.5 threshold for random distribution, indicating a strong inherent spatial structure that is likely driven by the physiological signal rather than noise. While the Sham set has a high Hopkins value, its sharp decline in Silhouette score moving from $k=2$ ($0.46$) to $k=3$ ($0.25$) suggests a lack of stable sub-structures compared to the Low-Freq set, which preserves more consistent internal cohesion across higher $k$ values. Notably, $k=2$ emerges as the most mathematically stable partition for the cognitive features, aligning with our high-contrast cog_binary label and providing a strong geometric foundation for the subsequent clinical alignment benchmarking.
    
    ## Clustering methods
    """
    
    # Use Ward's linkage as it minimizes variance within clusters
    Z = linkage(FEATURES_SCALED['low_freq'], method='ward')
    
    plt.figure(figsize=(12, 7))
    dendrogram(Z, truncate_mode='lastp', p=30, leaf_rotation=90., leaf_font_size=8., show_contracted=True)
    plt.title("Hierarchical Clustering Dendrogram (Low-Freq)")
    plt.xlabel("Cluster Size (or Patient ID)")
    plt.ylabel("Ward's Distance")
    plt.axhline(y=15, color='r', linestyle='--') # Test "cut line"
    plt.show()
    
    # K = 2 or 3 across all
    k_values = [2, 3]
    X = FEATURES_SCALED['low_freq']
    
    clustering_results = {}
    
    for k in k_values:
      # 1. Hierarchical (main)
      clustering_results[f'Hierarchical_k{k}'] = AgglomerativeClustering(n_clusters=k).fit_predict(X)
    
      # 2. KMeans (baseline)
      clustering_results[f'KMeans_k{k}'] = KMeans(n_clusters=k, random_state=RANDOM_STATE, n_init=10).fit_predict(X)
    
      # 3. GMM (probabilistic)
      clustering_results[f'GMM_k{k}'] = GaussianMixture(n_components=k, random_state=RANDOM_STATE).fit(X).predict(X)
    
    """## Alignment Analysis"""
    
    targets = {'Binary': y_binary, 'Tiered': y_tiered, 'Diagnosis': y_diag}
    alignment_table = []
    
    for algo_k, assignments in clustering_results.items():
      res = {'Model': algo_k}
      for target_name, target_values in targets.items():
        # Calc NMI
        score = normalized_mutual_info_score(assignments, target_values)
        res[target_name] = score
      alignment_table.append(res)
    
    # To df for visualizing
    df_alignment = pd.DataFrame(alignment_table).sort_values(by='Binary', ascending=False)
    print(df_alignment)
    
    """The unsupervised analysis identifies Hierarchical Clustering with $k=3$ as the optimal model for capturing the neurophysiological structure of the dataset, achieving the highest alignment with clinical cognitive status (NMI = 0.19). While the geometry analysis suggested $k=2$ as a more stable structural split due to its silhouette score, the superior alignment of the $k=3$ model implies that the EEG features identify a latent 'transitionary' phenotype within the cognitive spectrum that the binary clinical labels do not explicitly capture. Furthermore, the consistent outperformance of Hierarchical methods over K-Means (NMI = 0.125) indicates that the underlying feature manifold is non-linear and hierarchical in nature. This suggests that Parkinsonian cognitive decline is better represented by nested connectivity patterns rather than discrete, spherical clusters, justifying the move toward more complex subgroup characterization.
    
    In this context, the NMI of 0.191 achieved by the Hierarchical k=3 model represents a meaningful alignment between unsupervised EEG phenotypes and clinical cognitive status. While this value reflects the inherent overlap and variability in neurophysiological signals, it demonstrates that the low-frequency feature set successfully extracts a cognitive signal that is significantly more robust than random distribution, providing a mathematical basis for the existence of distinct PD cognitive subgroups.
    """
    
    # Color the t-SNE by the winning model (Hierarchical k=3)
    winning_clusters = clustering_results['Hierarchical_k3']
    
    plt.figure(figsize=(10, 7))
    sns.scatterplot(
      x=X_coords[:, 0], y=X_coords[:, 1],
      hue=winning_clusters, palette='magma', s=100, alpha=0.8
    )
    plt.title("Winning Model: Hierarchical (k=3) on t-SNE Landscape")
    plt.xlabel("t-SNE 1")
    plt.ylabel("t-SNE 2")
    plt.legend(title="Cluster ID")
    plt.show()
    
    """This validates the use of high-dimensional clustering over simple 2D visual inspection, as the former preserves the manifold's integrity that t-SNE fragments."""
    
    mapping_data = pd.DataFrame({
      'C_ID': clustering_results['Hierarchical_k3'],           # Cluster ID (0, 1, 2)
      'X': np.round(X_coords[:, 0], 2), # Rounded for readability
      'Y': np.round(X_coords[:, 1], 2),
      'CB': y_binary,                    # Clinical Binary (0/1)
      'CT': y_tiered
    })
    
    # Sort by Cluster ID to make the patterns visible
    #print(mapping_data.sort_values('C_ID').to_string(index=False))
    
    """The brain waves "see" a difference between Impaired and Not-Impaired, but they don't see a big difference between "Standard" and "Preservcl"""
    
    def analyze_existing_hierarchical_clusters(features_dict, cluster_labels, feature_names = None):
    
        # 1. Setup the data
        X_raw = features_dict["low_freq"]
    
        # Feature names
        if feature_names is None:
            # Fallback if profile_cols isn't passed
            feature_names = [f"Freq_{i}" for i in range(X_raw.shape[1])]
    
        records = []
    
        # 2. Compute Centroids based on the existing labels
        unique_clusters = np.unique(cluster_labels)
    
        for cluster in sorted(unique_clusters):
            # Filter for the specific hierarchical group
            cluster_mask = (cluster_labels == cluster)
            if cluster_mask.sum() == 0: continue
    
            centroid_values = X_raw[cluster_mask].mean(axis=0)
    
            for fname, val in zip(feature_names, centroid_values):
                records.append({
                    'cluster': cluster,
                    'feature': fname,
                    'centroid_value': val,
                    'cluster_size': cluster_mask.sum()
                })
    
        df_centroids = pd.DataFrame(records)
    
        # Calculate Z-Scores to show how each cluster deviates from the average patient
        df_centroids['z_score'] = df_centroids.groupby('feature')['centroid_value'].transform(
            lambda x: (x - x.mean()) / (x.std() + 1e-9)
        )
    
        return df_centroids
    
    # Execute using the existing Cog_Stage labels
    df_centroids_hier = analyze_existing_hierarchical_clusters(FEATURES, winning_clusters, feature_names=profile_cols)
    
    # See the "Clinical Fingerprint"
    profile_table = df_centroids_hier.pivot(index='feature', columns='cluster', values='z_score')
    print("Hierarchical Cluster Profiles (Z-Scores):")
    print(profile_table)
    
    """**Now to profile clinical groups instead of naturally formed EEG clusters**"""
    
    df_centroids_clin = analyze_existing_hierarchical_clusters(FEATURES, y_tiered, feature_names=profile_cols)
    
    profile_table_clin = df_centroids_clin.pivot(index='feature', columns='cluster', values='z_score')
    print("Clinical Cluster Profiles (Z-Scores):")
    print(profile_table_clin)
    
    # Create the DataFrame using the reconstructed names
    profile_df = pd.DataFrame(FEATURES["low_freq"], columns=profile_cols)
    profile_df['Unsupervised_Cluster'] = winning_clusters
    profile_df['Clinical_Stage'] = y_tiered
    
    # Subplot (Clinical, Unsupervised)
    fig, axes = plt.subplots(2, 1, figsize=(18, 14), sharex=True)
    
    # Unsupervised Clusters (data-driven)
    df_melted_unsup = profile_df.drop(columns=['Clinical_Stage']).melt(
        id_vars='Unsupervised_Cluster', var_name='Biomarker', value_name='Value')
    sns.lineplot(data=df_melted_unsup, x='Biomarker', y='Value', hue='Unsupervised_Cluster',
                 palette='plasma', linewidth=2.5, marker='o', ax=axes[0])
    axes[0].set_title("Spectral Profile by UNSUPERVISED CLUSTERS (Hierarchical k=3)", fontsize=16)
    axes[0].set_ylabel("Log Power / Ratio Value")
    
    
    # Clinical Stages
    df_melted_clin = profile_df.drop(columns=['Unsupervised_Cluster']).melt(
        id_vars='Clinical_Stage', var_name='Biomarker', value_name='Value')
    sns.lineplot(data=df_melted_clin, x='Biomarker', y='Value', hue='Clinical_Stage',
                 palette='viridis', linewidth=2.5, marker='o', ax=axes[1])
    axes[1].set_title("Spectral Profile by CLINICAL STAGES (Z-Score Based)", fontsize=16)
    axes[1].set_ylabel("Log Power / Ratio Value")
    
    plt.xticks(rotation=90, fontsize=10)
    plt.xlabel("Channel-Specific Features (8 Channels x [Delta, Theta, L-Alpha, TAR] + Global TAR)")
    plt.tight_layout()
    plt.show()
    
    """The dominance of the TAR over raw power values suggests that the relative distribution of neural oscillations is the primary indicator of cognitive status. The relationship observed, where increasing impairment stages  result in a corresponding increase in TAR magnitude, validates this ratio as a robust biomarker for staging cognitive decline in this context.
    
    There is an evident morphological similarity between the two plots. The remarkable symmetry between the clinical stage profiles and the unsupervised cluster centroids suggests that the mathematical clustering is not identifying arbitrary noise, but is accurately tracking the neurophysiological signature of cognitive decline.
    
    While the unsupervised hierarchical clustering ($k=3$) identifies a high-internal-cohesion "Super-Impaired" phenotype (Cluster 0), the crossover of intermediate cluster profiles suggests that mathematical clustering alone may not perfectly capture the linear transition of neurodegeneration.
    """
    
    # JUST FOR VISUALIZATION
    # Identify the last 15 features (TARs and Global TAR)
    last_15_cols = profile_cols[-15:]
    
    subset_cols_unsup = list(last_15_cols) + ['Unsupervised_Cluster']
    subset_cols_clin = list(last_15_cols) + ['Clinical_Stage']
    
    # Subplot (Clinical, Unsupervised)
    fig, axes = plt.subplots(2, 1, figsize=(15, 15), sharex=True)
    
    # Unsupervised Clusters
    df_melted_unsup = profile_df[subset_cols_unsup].melt(
        id_vars='Unsupervised_Cluster', var_name='Biomarker', value_name='Value')
    
    sns.lineplot(data=df_melted_unsup, x='Biomarker', y='Value', hue='Unsupervised_Cluster',
                 palette='plasma', linewidth=2.5, marker='o', ax=axes[0])
    axes[0].set_title("Spectral Profile by UNSUPERVISED CLUSTERS (Hierarchical k=3)", fontsize=20)
    axes[0].set_ylabel("Log Power / Ratio Value", fontsize=14)
    axes[0].legend(title='Unsupervised Clusters',
                   title_fontsize='16',   # The "color map" title size
                   fontsize='14',         # The individual cluster labels size
                   loc='upper left')      # Adjust location if it blocks data
    
    
    # Clinical Stages
    df_melted_clin = profile_df[subset_cols_clin].melt(
        id_vars='Clinical_Stage', var_name='Biomarker', value_name='Value')
    
    sns.lineplot(data=df_melted_clin, x='Biomarker', y='Value', hue='Clinical_Stage',
                 palette='viridis', linewidth=2.5, marker='o', ax=axes[1])
    axes[1].set_title("Spectral Profile by CLINICAL STAGES (Z-Score Based)", fontsize=20)
    axes[1].set_ylabel("Log Power / Ratio Value", fontsize=14)
    axes[1].legend(title='Clinical Stages',
                   title_fontsize='16',   # The "color map" title size
                   fontsize='14',         # The individual stage labels size
                   loc='upper left')
    
    # Formatting
    plt.xticks(rotation=45, ha='right', fontsize=14) # Reduced rotation for better fit
    plt.xlabel("Channel-Specific Ratios and Global TAR", fontsize=14)
    plt.tight_layout()
    plt.show()
    
    """## Comparison"""
    
    def run_unsupervised_pipeline(feature_matrix, participants_df, valid_ids, title="Feature Set"):
      # Labes + Scale
      df_idx = participants_df.set_index("participant_id").loc[valid_ids]
      X_scaled = StandardScaler().fit_transform(feature_matrix)
    
      # BINARY ALIGNMENT (k=2)
      # Testing how well the brain separates into Impaired vs Not-Impaired
      clusters_2 = AgglomerativeClustering(n_clusters=2, linkage='ward').fit_predict(X_scaled)
      nmi_binary = normalized_mutual_info_score(df_idx["cog_binary"], clusters_2)
      nmi_dx = normalized_mutual_info_score(df_idx["GROUP"], clusters_2)
    
      #  TIERED ALIGNMENT (k=3)
      # Testing the 3-tier clinical resolution
      clusters_3 = AgglomerativeClustering(n_clusters=3, linkage='ward').fit_predict(X_scaled)
      nmi_tier = normalized_mutual_info_score(df_idx["cog_tier"], clusters_3)
    
      return {
        "NMI: Diagnosis (k=2)": nmi_dx,
        "NMI: Binary (k=2)": nmi_binary,
        "NMI: Tiered (k=3)": nmi_tier
      }
    
    def run_clean_comparison(constructions, participants_df, valid_ids, n_clust = 3):
        final_report = []
        df_idx = participants_df.set_index("participant_id").loc[valid_ids]
    
        for name, X in constructions.items():
            X_scaled = StandardScaler().fit_transform(X)
    
            clusterer = AgglomerativeClustering(n_clusters=n_clust, linkage='ward')
            clusters = clusterer.fit_predict(X_scaled)
    
            sil = silhouette_score(X_scaled, clusters)
    
            #h_stat = hopkins_statistic(X_scaled)[0]
    
            nmi_ternary = normalized_mutual_info_score(df_idx['cog_tier'], clusters)
            nmi_binary = normalized_mutual_info_score(df_idx['cog_binary'], clusters)
            nmi_dx = normalized_mutual_info_score(df_idx['GROUP'], clusters)
    
            final_report.append({
                "Feature Set": name,
                "Silhouette": sil,
                "NMI: Tiered": nmi_ternary,
                "NMI: Binary": nmi_binary,
                "NMI: Diagnosis": nmi_dx
            })
    
        return pd.DataFrame(final_report)
    
    
    clean_analysis_results_2 = run_clean_comparison(FEATURES, participants, subs_list, 2)
    print("k=2")
    print(clean_analysis_results_2)
    clean_analysis_results_3 = run_clean_comparison(FEATURES, participants, subs_list, 3)
    print("k=3")
    print(clean_analysis_results_3)
    
    """Clustering quality differed substantially across feature constructions. The Low-Freq feature set demonstrated a strong intrinsic structure, with a high silhouette score (0.38 for k=3), indicating clear non-random clustering tendency and moderate cluster separation. It also showed the strongest alignment with clinical variables, achieving the highest NMI with both tiered cognition (0.15), binary cognition (0.19), and diagnosis (0.12). In contrast, the Full PSD features exhibited weak clinical alignment (NMI around 0.01-0.02) despite their clusterability, suggesting that high-dimensional spectral features contain structure that is largely unrelated to disease or cognition. The Sham band showed intermediate behavior, with modest clusterability and partial alignment (NMI 0.06–0.13), but consistently weaker than the Low-Freq features. Together, these results indicate that the engineered Low-Frequency ratios capture clinically meaningful variance more effectively than broad or non-specific spectral representations.
    
    We've decided to bypass PCA for the clustering step because the Low-Freq features are already "information-dense" and hand-picked. While PCA is excellent for reducing noise in massive datasets, in this specific case, it acts as a "blurring" filter that merges distinct clinical signals into broad components, as evidenced by a big drop in NMI when PCA was introduced. By clustering directly on the scaled features, we preserve the mathematical integrity of the specific frequency ratios that distinguish cognitive states.
    """
    
    pd_mask = (participants['GROUP'] == 'PD').values
    X_pd_low = FEATURES["low_freq"][pd_mask]
    subs_pd = participants.loc[pd_mask, 'participant_id'].tolist()
    
    hc_mask = (participants['GROUP'] == 'Control').values
    X_hc_low = FEATURES["low_freq"][hc_mask]
    subs_hc = participants.loc[hc_mask, 'participant_id'].tolist()
    
    # Pipeline run
    results_pd = run_unsupervised_pipeline(X_pd_low, participants, subs_pd, title="PD Subgroup")
    results_hc = run_unsupervised_pipeline(X_hc_low, participants, subs_hc, title="Control Subgroup")
    
    print("\n-  PD SUBGROUP RESULTS  -")
    results_pd = run_unsupervised_pipeline(X_pd_low, participants, subs_pd, title="PD Subgroup")
    for metric, value in results_pd.items():
      print(f"{metric}: {value:.4f}")
    
    print("\n-  CONTROL SUBGROUP RESULTS  -")
    results_hc = run_unsupervised_pipeline(X_hc_low, participants, subs_hc, title="Control Subgroup")
    for metric, value in results_hc.items():
      print(f"{metric}: {value:.4f}")
    
    """The subgroup results provide the most compelling evidence yet for the validity of the low_freq features as a specific biomarker for Parkinson’s cognitive decline. In the PD group, the Binary NMI is maintained, as well as the Tiered NMI. This indicates that the unsupervised clusters align better with clinical labels when the "distraction" of healthy controls is removed. In stark contrast, the Control group shows almost zero alignment (Binary NMI: 0.009), confirming that the brain-behavior relationship captured by these EEG features is unique to the neurodegenerative process of PD rather than being a general signature of healthy cognitive variation. The 0.00 Diagnosis NMI is expected here, as there is no diagnostic variance within a single-group mask.
    
    This indicates that the identified EEG clusters are not arbitrary mathematical groupings, but rather biological manifestations of the frontal-executive deficit characteristic of Parkinson’s Disease.
    """
    
    low_freq_df = pd.DataFrame(FEATURES["low_freq"])
    
    # Correlations between tests & features
    correlations = {}
    for test in cognitive_cols:
      corrs = low_freq_df.corrwith(participants[test])
      correlations[test] = corrs
    
    corr_matrix = pd.DataFrame(correlations)
    
    plt.figure(figsize=(10, 8))
    sns.heatmap(corr_matrix, annot=False, cmap='RdBu_r', center=0)
    plt.title("Feature-to-Cognition Audit: Where is the signal?")
    plt.show()
    
    # Isolate PD
    pd_mask = (participants['GROUP'] == 'PD').values
    X_pd_scaled = StandardScaler().fit_transform(FEATURES["low_freq"][pd_mask])
    
    # Re-generate clusters (3)
    pd_clusterer = AgglomerativeClustering(n_clusters=3, linkage='ward')
    pd_clusters = pd_clusterer.fit_predict(X_pd_scaled)
    
    pd_analysis_df = participants[pd_mask].copy()
    pd_analysis_df['low_freq_cluster'] = pd_clusters
    
    nih_scores = ['NIH FICAT', 'NIH DCCST', 'NIH PCPST', 'NIH PSMT', 'NIH PVT']
    nih_audit = []
    
    for score in nih_scores:
        # Binary 'High/Low' label for this specific domain
        median_val = pd_analysis_df[score].median()
        binary_label = (pd_analysis_df[score] < median_val).astype(int)
    
        # NMI between the clusters & this test
        nmi = normalized_mutual_info_score(binary_label, pd_clusters)
    
        nih_audit.append({"Domain": score, "NMI": nmi})
    
    audit_results = pd.DataFrame(nih_audit).sort_values(by="NMI", ascending=False)
    print("NIH Domain Alignment Audit")
    print(audit_results)
    
    """The NIH Domain Alignment Audit confirms that the unsupervised EEG clusters are not general indicators of cognitive health, but specifically track frontal-executive function. The highest alignment was found with Inhibitory Control (FICAT, NMI = 0.16) and Processing Speed (PCPST, NMI = 0.10). The significantly lower NMI values for Vocabulary and Memory (PVT and PSMT) validate that the selected low-frequency EEG features are specialized biomarkers for the executive deficits most prevalent in Parkinson's Disease, rather than capturing non-specific cognitive variance.
    
    ## Permutation test
    """
    
    def run_permutation_test(true_labels, predicted_clusters, n_permutations=1000):
      # Observed NMI
      observed_nmi = normalized_mutual_info_score(true_labels, predicted_clusters)
    
      # Generate the Null Distrib
      null_nmis = []
    
      for _ in range(n_permutations):
        shuffled = np.random.permutation(true_labels)
        null_nmis.append(normalized_mutual_info_score(shuffled, predicted_clusters))
    
    
      p_value = (np.sum(np.array(null_nmis) >= observed_nmi) + 1) / (n_permutations + 1)
    
      return observed_nmi, null_nmis, p_value
    
    # Hierarchical k=3 clusters
    
    print("For cog_binary")
    obs_nmi, null_dist, p_val = run_permutation_test(participants['cog_binary'].values, winning_clusters)
    print(f"Observed NMI: {obs_nmi:.4f}")
    print(f"Empirical P-Value: {p_val:.4f}")
    
    print()
    print("For cog_tier")
    obs_nmi, null_dist, p_val = run_permutation_test(participants['cog_tier'].values, winning_clusters)
    print(f"Observed NMI: {obs_nmi:.4f}")
    print(f"Empirical P-Value: {p_val:.4f}")
    
    print()
    print("For GROUP")
    obs_nmi, null_dist, p_val = run_permutation_test(participants['GROUP'].values, winning_clusters)
    print(f"Observed NMI: {obs_nmi:.4f}")
    print(f"Empirical P-Value: {p_val:.4f}")
    
    """To ensure the generalizability of the unsupervised findings, permutation tests ($n=1,000$) were performed across three separate labeling schemas: Group (PD vs. HC), Binary Cognitive Status, and Tiered Cognitive Status. In all three instances, the empirical p-value was $< 0.001$. This uniform significance suggests that the hierarchical clusters are not merely aligned with a single clinical variable, but are instead capturing a comprehensive neurophysiological profile that encompasses both the primary diagnosis of Parkinson's Disease and the subsequent stages of cognitive decline.
    
    ## Conclusions unsupervised
    
    Together, these findings demonstrate that engineered low-frequency EEG features exhibit a statistically significant intrinsic structure that aligns preferentially with executive cognitive impairment ($NMI = 0.191$, $p < 0.001$) rather than clinical diagnosis ($NMI = 0.117$). This alignment is highly specific to the PD cohort, where cognitive decline is linked to pathological brain slowing; in contrast, healthy controls showed no comparable alignment ($NMI = 0.008$), suggesting the identified clusters represent a disease-specific neurophysiological phenotype. Furthermore, the total absence of structural correspondence in sham bands and the failure of permutation controls to replicate these NMIs confirm that this organization reflects frequency-specific neurobiological reality rather than high-dimensional geometric artifacts. Ultimately, this unsupervised approach proves that the brain's spectral power in the low-frequency range provides a more accurate reflection of a patient's functional cognitive state than their medical diagnosis alone.
    """
    
    print("Unsupervised analysis complete.")